title: FINOS AI Readiness - AI Governance Framework

risk_classification:
  RC: Regulatory and Compliance
  OP: Operational
  SEC: Security

mitigation_classification:
  PREV: Preventative
  DET: Detective

external_risks:
  OWASP-LLM_2025_LLM01:
    title: "OWASP: Prompt Injection"
    url: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/"
  OWASP-LLM_2025_LLM02:
    title: "OWASP: Sensitive Information Disclosure"
    url: "https://genai.owasp.org/llmrisk/llm022025-sensitive-information-disclosure/"
  OWASP-LLM_2025_LLM03:
    title: "OWASP: Supply Chain Vulnerabilities"
    url: "https://genai.owasp.org/llmrisk/llm032025-supply-chain/"
  OWASP-LLM_2025_LLM04:
    title: "OWASP: Data and Model Poisoning"
    url: "https://genai.owasp.org/llmrisk/llm042025-data-and-model-poisoning/"
  OWASP-LLM_2025_LLM05:
    title: "OWASP: Improper Output Handling"
    url: "https://genai.owasp.org/llmrisk/llm052025-improper-output-handling/"
  OWASP-LLM_2025_LLM06:
    title: "OWASP: Excessive Agency"
    url: "https://genai.owasp.org/llmrisk/llm062025-excessive-agency/"
  OWASP-LLM_2025_LLM07:
    title: "OWASP: System Prompt Leakage"
    url: "https://genai.owasp.org/llmrisk/llm072025-system-prompt-leakage/"
  OWASP-LLM_2025_LLM08:
    title: "OWASP: Vector and Embedding Weaknesses"
    url: "https://genai.owasp.org/llmrisk/llm082025-vector-and-embedding-weaknesses/"
  OWASP-LLM_2025_LLM09:
    title: "OWASP: Misinformation"
    url: "https://genai.owasp.org/llmrisk/llm092025-misinformation/"
  OWASP-LLM_2025_LLM10:
    title: "OWASP: Unbounded Consumption"
    url: "https://genai.owasp.org/llmrisk/llm102025-unbounded-consumption/"
  NIST-600_2024_2-01:
    title: "NIST: CBRN Information or Capabilities"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-02:
    title: "NIST: Confabulation"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-03:
    title: "NIST: Dangerous, Violent, or Hateful Content"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-04:
    title: "NIST: Data Privacy"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-05:
    title: "NIST: Environmental Impacts"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-06:
    title: "NIST: Harmful Bias and Homogenization"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-07:
    title: "NIST: Human-AI Configuration"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-08:
    title: "NIST: Information Integrity"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-09:
    title: "NIST: Information Security"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-10:
    title: "NIST: Intellectual Property"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-11:
    title: "NIST: Obscene, Degrading, and/or Abusive Content"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"
  NIST-600_2024_2-12:
    title: "NIST: Value Chain and Component Integration"
    url: "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf"

document_status:
  - name: Pre-Draft
    description: "Initial brainstorming or collection of ideas, notes, and outlines. The document is not yet formally written."
  - name: Draft
    description: "The document is in the early stages of development, with content being written and structured but not yet polished."
  - name: Review
    description: "The document is being reviewed by others for feedback. It may undergo multiple iterations at this stage."
  - name: Approved
    description: "The document is in its final form and has been approved by the AI Governance Framework Maintainers team."

collections:
  risks:
    output: true
  mitigations:
    output: true
