title: FINOS AI Readiness - AI Governance Framework

risk_classification:
  RC: Regulatory and Compliance
  OP: Operational
  SEC: Security

mitigation_classification:
  PREV: Preventative
  DET: Detective

document_status:
  - name: Pre-Draft
    description: "Initial brainstorming or collection of ideas, notes, and outlines. The document is not yet formally written."
  - name: Draft
    description: "The document is in the early stages of development, with content being written and structured but not yet polished."
  - name: Working-Group-Approved
    description: "The document is in its final form and has been approved by the AIGF team."
  - name: Published
    description: "The publication of an Approved Specification in a publicly accessible manner."

collections:
  risks:
    output: true
  mitigations:
    output: true
